'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDatabaseServerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatabaseServerName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVDatabaseServerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVDatabaseServerName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDatabaseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatabaseName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVDatabaseName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVDatabaseName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDatabaseOwnerUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatabaseOwnerUsername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVDatabaseOwnerUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVDatabaseOwnerUsername As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDatabaseOwnerPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatabaseOwnerPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVDatabaseOwnerPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVDatabaseOwnerPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAdministratorUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdministratorUsername As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVAdministratorUsername control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVAdministratorUsername As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAdministratorPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdministratorPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVAdministratorPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVAdministratorPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAdministratorRoleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdministratorRoleName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVAdministratorRoleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVAdministratorRoleName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAdministratorFirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdministratorFirstname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVAdministratorFirstname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVAdministratorFirstname As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAdministratorLastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdministratorLastname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVAdministratorLastname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVAdministratorLastname As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAdministratorEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdministratorEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RVAdministratorEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RVAdministratorEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDownloadProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDownloadProject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinish As Global.System.Web.UI.WebControls.Button
End Class
